services:
  - type: web
    name: vaseline-gluta-hya
    env: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
